# Generated by Django 6.0.3 on 2026-03-15 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=50)),
            ],
            options={"db_table": "items_hero"},
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
            ],
            options={"db_table": "items_item"},
        ),
        migrations.CreateModel(
            name="Cosmetic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("price", models.FloatField(default=0)),
                ("quantity", models.IntegerField(default=0)),
                ("hero", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="visualisation.hero")),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visualisation.item",
                    ),
                ),
            ],
            options={"db_table": "items_cosmetic"},
        ),
        migrations.CreateModel(
            name="PriceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="visualisation.item")),
            ],
            options={"db_table": "items_pricerecord"},
        ),
    ]
