# Generated by Django 6.0.3 on 2026-03-16 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visualisation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cosmetic",
            name="hero",
        ),
        migrations.RemoveField(
            model_name="cosmetic",
            name="item",
        ),
        migrations.RemoveField(
            model_name="pricerecord",
            name="item",
        ),
        migrations.DeleteModel(
            name="Hero",
        ),
        migrations.DeleteModel(
            name="Cosmetic",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="PriceRecord",
        ),
    ]
