# Generated by Django 2.1.5 on 2026-03-12 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(max_length=20, unique=True)),
                ('hero_type', models.CharField(max_length=20)),
                ('item1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_item1', to='mocktrade.Cosmetic')),
                ('item2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_item2', to='mocktrade.Cosmetic')),
            ],
        ),
        migrations.CreateModel(
            name='MarketRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktrade.Cosmetic')),
            ],
        ),
        migrations.CreateModel(
            name='MockTrading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('asset1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset1_users', to='mocktrade.Cosmetic')),
                ('asset10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset10_users', to='mocktrade.Cosmetic')),
                ('asset2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset2_users', to='mocktrade.Cosmetic')),
                ('asset3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset3_users', to='mocktrade.Cosmetic')),
                ('asset4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset4_users', to='mocktrade.Cosmetic')),
                ('asset5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset5_users', to='mocktrade.Cosmetic')),
                ('asset6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset6_users', to='mocktrade.Cosmetic')),
                ('asset7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset7_users', to='mocktrade.Cosmetic')),
                ('asset8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset8_users', to='mocktrade.Cosmetic')),
                ('asset9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset9_users', to='mocktrade.Cosmetic')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('message_post_today', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='mocktrading',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mocktrade.UserAccount'),
        ),
    ]
