# Generated by Django 6.0.3 on 2026-03-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messageboard", "0004_auto_20260311_1339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
