# Generated by Django 5.1.5 on 2026-03-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0005_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
